export const products = [
    { id: 1, name: "Performance Tires", price: 14999, image: "/assets/images/products/tires.jpg" },
    { id: 2, name: "Sport Steering Wheel", price: 10999, image: "/assets/images/products/steering-wheel.jpg" },
    { id: 3, name: "Carbon Fiber Spoiler", price: 22999, image: "/assets/images/products/spoiler.jpg" },
    { id: 4, name: "LED Headlights", price: 6599, image: "/assets/images/products/headlights.jpg" },
    { id: 5, name: "Brake Kit", price: 13499, image: "/assets/images/products/brakes.jpg" },
    { id: 6, name: "Air Filter", price: 2199, image: "/assets/images/products/air-filter.jpg" },
    { id: 7, name: "Exhaust System", price: 29999, image: "/assets/images/products/exhaust.jpg" },
    { id: 8, name: "Alloy Wheels", price: 18999, image: "/assets/images/products/wheels.jpg" },
    { id: 9, name: "Suspension Kit", price: 25999, image: "/assets/images/products/suspension.jpg" },
    { id: 10, name: "Turbocharger", price: 44999, image: "/assets/images/products/turbo.jpg" },
    { id: 11, name: "Car Battery", price: 9699, image: "/assets/images/products/battery.jpg" },
    { id: 12, name: "Spark Plugs", price: 1499, image: "/assets/images/products/spark-plugs.jpg" },
    { id: 13, name: "Oil Filter", price: 1099, image: "/assets/images/products/oil-filter.jpg" },
    { id: 14, name: "Radiator", price: 11999, image: "/assets/images/products/radiator.jpg" },
    { id: 15, name: "Alternator", price: 14999, image: "/assets/images/products/alternator.jpg" },
    { id: 16, name: "Starter Motor", price: 11299, image: "/assets/images/products/starter.jpg" },
    { id: 17, name: "Fuel Pump", price: 6599, image: "/assets/images/products/fuel-pump.jpg" },
    { id: 18, name: "Timing Belt", price: 3699, image: "/assets/images/products/timing-belt.jpg" },
    { id: 19, name: "Shock Absorbers", price: 5999, image: "/assets/images/products/shocks.jpg" },
    { id: 20, name: "Strut Bar", price: 5199, image: "/assets/images/products/strut-bar.jpg" },
    { id: 21, name: "ECU Tuning Kit", price: 22499, image: "/assets/images/products/ecu.jpg" },
    { id: 22, name: "Shift Knob", price: 2999, image: "/assets/images/products/shift-knob.jpg" },
    { id: 23, name: "Pedal Set", price: 4499, image: "/assets/images/products/pedals.jpg" },
    { id: 24, name: "Gauges Set", price: 9699, image: "/assets/images/products/gauges.jpg" },
    { id: 25, name: "Car Cover", price: 6699, image: "/assets/images/products/car-cover.jpg" }
];